/* The Pathfinder: The Astral Archive. Game-only renderer and orchestration. */
(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const C=window.ArchiveCore, THREE=window.THREE, DATA=window.PORTFOLIO;
if(!C||!THREE||!DATA||!window.ArchiveWorld||!window.ArchiveMotion||!window.ArchiveFX){$('#loading').hidden=true;$('#failure').hidden=false;return;}
const reduced=matchMedia('(prefers-reduced-motion:reduce)'), touch=matchMedia('(pointer:coarse)').matches;
const STORE='arjun-astral-archive-v1';
let renderer,scene,camera,composer,bloom,fxaa,grade,world,avatar,keyLight,combatFX;
let mode='title',frame=0,lastTime=0,time=0,quality=!touch,effects=!reduced.matches,soundOn=false,ready=false;
let yaw=.35,targetYaw=.35,pitch=.58,targetPitch=.58,distance=12.5,targetDistance=12.5;
let walkPhase=0,shake=0,hitstop=0,currentIsland=null,nearArchive=null,attack=null,attackQueued=false,travel=null,fallen=0,hudTime=0;
let audioContext,master,announcementTime=0,damageFlash=0;
const player=C.createPlayer(), keys=new Set(), stick={active:false,id:null,x:0,z:0,startX:0,startY:0};
const pointer={active:false,id:null,x:0,y:0,startX:0,startY:0,moved:false,button:0};
const enemies=[],effectsList=[],waves=[];
let lastFacing=0,motionBank=0,motionSpeed=0,groundLast=true,landingSpring=0,fireCast=0,flightBlend=0;
let save={discovered:[],guardian:false};try{save=C.parseSave(localStorage.getItem(STORE));}catch{}
const discovered=new Set(save.discovered);let guardianDefeated=save.guardian;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const linear=n=>new THREE.Color(n).convertSRGBToLinear();
const vec=new THREE.Vector3(),cameraTarget=new THREE.Vector3(),lookTarget=new THREE.Vector3();
const partCount=touch?260:520,particles=Array.from({length:partCount},()=>({life:0,x:0,y:0,z:0,vx:0,vy:0,vz:0,color:new THREE.Color()}));let particleIndex=0,particleMesh,particlePositions,particleColors;
function persist(){try{localStorage.setItem(STORE,JSON.stringify({version:1,discovered:[...discovered],guardian:guardianDefeated}));}catch{}}
function announce(kicker,text){$('#announcement small').textContent=kicker;$('#announcement strong').textContent=text;$('#announcement').classList.add('visible');announcementTime=4;}
function audioInit(){
  if(audioContext){audioContext.resume();return;}
  try{audioContext=new (window.AudioContext||window.webkitAudioContext)();master=audioContext.createGain();master.gain.value=soundOn?.2:0;master.connect(audioContext.destination);
    for(const [i,hz] of [65.41,98,130.81,196].entries()){const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=hz;gain.gain.value=i===0?.045:.018;osc.connect(gain).connect(master);osc.start();}
  }catch{soundOn=false;}
}
function note(hz,duration=.2,volume=.2,type='sine',delay=0){if(!audioContext||!soundOn)return;const at=audioContext.currentTime+delay,osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type=type;osc.frequency.setValueAtTime(hz,at);gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(volume,at+.008);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);osc.connect(gain).connect(master);osc.start(at);osc.stop(at+duration+.02);}
function whoosh(heavy=false){if(!audioContext||!soundOn)return;const duration=heavy?.28:.16,n=Math.floor(audioContext.sampleRate*duration),buffer=audioContext.createBuffer(1,n,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*(1-i/n);const source=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain();source.buffer=buffer;filter.type='bandpass';filter.frequency.value=heavy?600:1600;filter.Q.value=.5;gain.gain.value=.45;source.connect(filter).connect(gain).connect(master);source.start();}
function toggleSound(){soundOn=!soundOn;audioInit();if(master)master.gain.setTargetAtTime(soundOn?.2:0,audioContext.currentTime,.2);$('#setting-sound span').textContent=soundOn?'On':'Off';$('#title-sound').innerHTML=`Sound ${soundOn?'on':'off'} <span>◌</span>`;}
function buildParticles(){const geo=new THREE.BufferGeometry();particlePositions=new Float32Array(partCount*3);particleColors=new Float32Array(partCount*3);geo.setAttribute('position',new THREE.BufferAttribute(particlePositions,3));geo.setAttribute('color',new THREE.BufferAttribute(particleColors,3));particleMesh=new THREE.Points(geo,new THREE.PointsMaterial({size:.14,vertexColors:true,blending:THREE.AdditiveBlending,transparent:true,depthWrite:false}));particleMesh.frustumCulled=false;scene.add(particleMesh);}
function sparks(x,y,z,color=0xffddac,count=25,power=5){for(let i=0;i<count;i++){const p=particles[particleIndex++%partCount];p.life=.5+Math.random()*.7;p.maxLife=p.life;p.x=x;p.y=y;p.z=z;p.vx=(Math.random()-.5)*power;p.vy=Math.random()*power*.7;p.vz=(Math.random()-.5)*power;p.color.copy(linear(color));}}
function ringEffect(x,z,color,radius=1,max=8,life=.6,y=.13){const mesh=new THREE.Mesh(new THREE.RingGeometry(.94,1,64),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));mesh.rotation.x=-Math.PI/2;mesh.position.set(x,y,z);mesh.scale.setScalar(radius);scene.add(mesh);effectsList.push({mesh,life,maxLife:life,start:radius,end:max});return mesh;}
function buildEnemyModels(){for(const i of C.ISLANDS.filter(i=>i.id!=='gate')){const e=C.createEnemy(i.x-3.3,i.z+3.2);e.model=world.sentinel(false);e.model.g.position.set(e.x,0,e.z);e.label=document.createElement('div');e.label.className='enemy-tag';$('#world-labels').append(e.label);enemies.push(e);}const boss=C.createEnemy(0,-39,true);boss.model=world.sentinel(true);boss.model.g.position.set(0,0,-39);if(guardianDefeated){boss.dead=true;boss.hp=0;boss.model.g.visible=false;}enemies.push(boss);}
function createLabels(){for(const shrine of world.shrines){const label=document.createElement('div');label.className='world-label';label.innerHTML=`<small>${shrine.chapter} / ARCHIVE</small><strong>${escape(shrine.name)}</strong><i></i>`;$('#world-labels').append(label);shrine.label=label;shrine.active=discovered.has(shrine.id);}}
function setQuality(){if(!renderer)return;const ratio=Math.min(devicePixelRatio||1,quality?1.6:1);renderer.setPixelRatio(ratio);renderer.setSize(innerWidth,innerHeight);composer.setPixelRatio(ratio);composer.setSize(innerWidth,innerHeight);bloom.enabled=quality;fxaa.uniforms.resolution.value.set(1/(innerWidth*ratio),1/(innerHeight*ratio));$('#setting-quality span').textContent=quality?'Cinematic':'Performance';}
function init(){try{
  if(!THREE||!C||!window.ArchiveWorld||!DATA)throw new Error('A local game dependency is missing.');
  renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:false,powerPreference:'high-performance'});renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.82;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  scene=new THREE.Scene();scene.fog=new THREE.FogExp2(linear(0x638491),.0048);camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,650);camera.position.set(54,35,60);
  scene.add(new THREE.HemisphereLight(0xc5e8f0,0x445867,.48));keyLight=new THREE.DirectionalLight(0xffedcf,1.15);keyLight.position.set(-35,55,-25);keyLight.castShadow=true;keyLight.shadow.mapSize.set(touch?1024:2048,touch?1024:2048);Object.assign(keyLight.shadow.camera,{left:-29,right:29,top:29,bottom:-29,near:1,far:160});keyLight.shadow.camera.updateProjectionMatrix();keyLight.shadow.bias=-.00025;keyLight.shadow.normalBias=.045;scene.add(keyLight);scene.add(keyLight.target);const rim=new THREE.DirectionalLight(0x83cce0,.3);rim.position.set(25,20,45);scene.add(rim);
  $('#load-message').textContent='Awakening the archives…';world=ArchiveWorld(THREE,C).build(scene,touch);avatar=world.traveler();combatFX=ArchiveFX(THREE,scene,avatar,touch);lastFacing=player.angle;buildEnemyModels();buildParticles();createLabels();
  composer=new THREE.EffectComposer(renderer);composer.addPass(new THREE.RenderPass(scene,camera));bloom=new THREE.UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.16,.3,.96);composer.addPass(bloom);fxaa=new THREE.ShaderPass(THREE.FXAAShader);composer.addPass(fxaa);
  // Compress post-bloom highlights without clipping hue, then encode linear output to sRGB once.
  grade=new THREE.ShaderPass({uniforms:{tDiffuse:{value:null}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform sampler2D tDiffuse;varying vec2 vUv;void main(){vec3 c=texture2D(tDiffuse,vUv).rgb;float v=dot(vUv-.5,vUv-.5);c=max(c,vec3(0.));c*=1.-smoothstep(.1,.5,v)*.18;float peak=max(c.r,max(c.g,c.b));float shoulder=.65+.35*(1.-exp(-max(peak-.65,0.)/.35));if(peak>.65)c*=shoulder/peak;vec3 lo=c*12.92;vec3 hi=1.055*pow(c,vec3(1./2.4))-.055;c=mix(lo,hi,step(vec3(.0031308),c));gl_FragColor=vec4(c,1.);}'});composer.addPass(grade);setQuality();
  ready=true;renderJournal();updateHUD();$('#loading').classList.add('complete');setTimeout(()=>{$('#loading').hidden=true;},650);if(discovered.size)$('#continue-note').textContent=`${discovered.size} OF 5 ARCHIVES AWAKENED · YOUR JOURNEY CONTINUES`;$('#setting-effects span').textContent=effects?'On':'Off';if(touch)document.body.classList.add('touch');requestFrame();
}catch(error){console.error('Astral Archive initialization:',error);$('#loading').hidden=true;$('#failure').hidden=false;}}
function start(){if(!ready)return;mode='playing';$('#title-screen').hidden=true;$('#hud').hidden=false;document.body.classList.add('playing');audioInit();lastTime=0;$('#world').focus();announce('WELCOME, TRAVELER','Five archives. Your own path.');}
function clearInput(){keys.clear();stick.active=false;stick.x=stick.z=0;$('#touch-pad i').style.transform='';pointer.active=false;}
function paused(){return $$('dialog').some(d=>d.open)||!!travel;}
function closeDialogs(){for(const d of $$('dialog'))if(d.open)d.close();}
function openDialog(id){clearInput();const dialog=$('#'+id);if(!dialog.open)dialog.showModal();}
function renderJournal(){
  $('#archive-index').innerHTML=C.ISLANDS.map((i,index)=>`<article class="archive-row"><span>${i.chapter}</span><div><h3>${escape(i.name)}</h3><p>${discovered.has(i.id)?'Awakened':escape(i.subtitle)}</p></div><button data-read="${index}">Read ↗</button><button data-travel="${index}" aria-label="Travel to ${escape(i.name)}">⌖</button></article>`).join('');
  $$('[data-read]').forEach(b=>b.onclick=()=>openArchive(Number(b.dataset.read)));$$('[data-travel]').forEach(b=>b.onclick=()=>teleport(Number(b.dataset.travel)));
}
function renderPanel(panel){
  const tags=list=>`<div class="archive-tags">${list.map(s=>`<span>${escape(s)}</span>`).join('')}</div>`,bullets=list=>`<ul>${list.map(s=>`<li>${escape(s)}</li>`).join('')}</ul>`;let html='';
  if(panel.stats)html+=`<div class="archive-stats">${panel.stats.map(([n,label])=>`<div><strong>${escape(n)}</strong><small>${escape(label)}</small></div>`).join('')}</div>`;
  if(panel.bullets)html+=bullets(panel.bullets);const sections=panel.sections==='skills'?DATA.skills:panel.sections;
  if(Array.isArray(sections))for(const s of sections){if(s.h)html+=`<h4>${escape(s.h)}</h4>`;if(s.ss)html+=`<p class="archive-sub">${escape(s.ss)}</p>`;if(s.p)html+=`<p>${escape(s.p.replace('— the same genre you are playing right now.','with combo combat and enemy AI.'))}</p>`;if(s.bullets)html+=bullets(s.bullets);if(s.tags)html+=tags(s.tags);}
  if(panel.tags)html+=tags(panel.tags);if(panel.contact)html+=`<p>Thanks for exploring. If you have a role, a project, or an idea, I’d love to hear from you.</p><a class="primary" href="mailto:${escape(DATA.email)}">${escape(DATA.email)} ↗</a>`;return html;
}
function openArchive(index){const island=C.ISLANDS[index];if(!island)return;closeDialogs();$('#archive-kicker').textContent=`CHAPTER ${island.chapter} / ${island.subtitle.toUpperCase()}`;$('#archive-title').textContent=island.name;$('#archive-content').innerHTML=island.nodes.map(id=>{const n=DATA.nodes.find(n=>n.id===id);if(!n)return '';return `<section><h3>${escape(n.panel.title)}</h3><p class="archive-sub">${escape(n.panel.sub)}</p>${renderPanel(n.panel)}</section>`;}).join('');openDialog('archive-dialog');$('#archive-dialog').scrollTop=0;}
function teleport(index){const i=C.ISLANDS[index];if(!i)return;closeDialogs();if(mode==='title')start();clearInput();travel={island:i,t:0,moved:false};$('#transition span').textContent=i.name;$('#transition').classList.add('active');}
function discover(){
  if(mode!=='playing'||paused()||!nearArchive||player.hp<=0)return;const index=C.ISLANDS.findIndex(i=>i.id===nearArchive.id);if(discovered.has(nearArchive.id)){openArchive(index);return;}
  discovered.add(nearArchive.id);nearArchive.active=true;player.checkpoint={x:player.x,z:player.z};player.hp=Math.min(100,player.hp+35);player.resonance=100;persist();renderJournal();ringEffect(nearArchive.x,nearArchive.z,nearArchive.color,1,10,1.2);sparks(nearArchive.x,3,nearArchive.z,nearArchive.color,70,7);
  [392,523.25,659.25,783.99].forEach((n,i)=>note(n,1.1,.13,'sine',i*.1));announce(`ARCHIVE ${nearArchive.chapter} AWAKENED`,nearArchive.name);if(discovered.size===5){announce('ALL FIVE ARCHIVES AWAKENED','A curious mind. A world of possibilities.');ringEffect(player.x,player.z,0xffddac,1,18,2);}
}
function movement(){let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);if(stick.active){x=stick.x;z=stick.z;}return {x:x*Math.cos(yaw)+z*Math.sin(yaw),z:z*Math.cos(yaw)-x*Math.sin(yaw),sprint:keys.has('ControlLeft')};}
function doDash(){if(mode!=='playing'||paused())return;const input=movement();if(C.startDash(player,input.x,input.z)){attack=null;attackQueued=false;combatFX.resetTrail();whoosh();note(82,.3,.18,'sawtooth');sparks(player.x,player.y+1,player.z,0x84eee4,30,3);}}
function doJump(){if(mode==='playing'&&!paused()&&C.startJump(player)){if(player.flying){attack=null;attackQueued=false;combatFX.resetTrail();note(110,.55,.2,'sawtooth');note(440,.5,.12);sparks(player.x,player.y+.5,player.z,0x6bddff,35,5);announce('FLIGHT SYSTEMS ONLINE','WASD to fly · Shift to boost · Space to land');}else{note(180,.14,.12,'sine');sparks(player.x,Math.max(0,player.y),player.z,0xd6e6d5,8,2);}}}
function doAttack(){
  if(mode!=='playing'||paused())return;if(player.attackTime>0){if(player.attackTime<player.attackDuration*.55)attackQueued=true;return;}
  const airborne=player.flying||(!player.grounded&&player.jumps===2),range=airborne?28:7;
  const closest=enemies.filter(e=>!e.dead&&(airborne?C.canHitAir(player,{x:e.x,y:e.model.targetY,z:e.z},range):Math.hypot(e.x-player.x,e.z-player.z)<range)).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z))[0];
  if(closest)player.angle=Math.atan2(closest.x-player.x,closest.z-player.z);const action=C.startAttack(player);if(action){attack={...action,target:closest||null,t:0,hit:false};if(!action.air)whoosh(action.heavy);}

}
function doPulse(){if(mode!=='playing'||paused()||!C.startPulse(player))return;attack=null;attackQueued=false;player.attackTime=0;fireCast=.6;combatFX.resetTrail();combatFX.explode(player.x,player.y,player.z);ringEffect(player.x,player.z,0xff7425,.5,12,.65,player.y+.13);sparks(player.x,player.y+1,player.z,0xff8128,110,15);whoosh(true);note(48,.9,.5,'triangle');note(85,.35,.2,'sawtooth');shake=effects?.16:0;for(const e of enemies)if(!e.dead&&Math.hypot(e.x-player.x,e.z-player.z)<12)hitEnemy(e,e.boss?5:4);}
function repulsorShot(action){
  const target=action.target,valid=target&&!target.dead&&C.canHitAir(player,{x:target.x,y:target.model.targetY,z:target.z},action.range);
  const from=avatar.palms[1].getWorldPosition(new THREE.Vector3()),to=valid?new THREE.Vector3(target.x,target.model.targetY,target.z):new THREE.Vector3(player.x+Math.sin(player.angle)*action.range,player.y+1.2,player.z+Math.cos(player.angle)*action.range);
  const delta=to.clone().sub(from),length=delta.length();const beam=new THREE.Mesh(new THREE.CylinderGeometry(.065,.065,length,10),new THREE.MeshBasicMaterial({color:0x7bdcfc,transparent:true,opacity:.85,blending:THREE.AdditiveBlending,depthWrite:false}));beam.position.copy(from).add(to).multiplyScalar(.5);beam.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());scene.add(beam);effectsList.push({mesh:beam,life:.13,maxLife:.13});sparks(from.x,from.y,from.z,0x79ddff,8,2);note(540,.13,.14,'triangle');if(valid){hitEnemy(target,action.damage);sparks(to.x,to.y,to.z,0xff9a59,16,4);}
}
function hitEnemy(e,damage){
  const died=C.damageEnemy(e,damage);sparks(e.x,e.model.targetY,e.z,e.boss?0xf3bf7a:0x9ce7e5,25,7);player.resonance=Math.min(100,player.resonance+damage*5);note(e.boss?94:196,.16,.22,'triangle');hitstop=effects?.045:0;shake=effects?.08:0;
  if(died){player.kills++;e.deathTime=0;ringEffect(e.x,e.z,e.boss?0xffd092:0x83e6df,.5,e.boss?15:5,e.boss?1.8:.7);sparks(e.x,e.model.targetY,e.z,0xf7dfac,e.boss?100:35,9);if(e.boss){guardianDefeated=true;persist();announce('THE AETHERBOUND RESTS','The gate is yours. The next chapter is unwritten.');[130.81,196,261.63,392].forEach((n,i)=>note(n,1.7,.18,'sine',i*.18));}}
}
function damage(amount){if(C.hurt(player,amount)){damageFlash=.32;shake=effects?.18:0;note(70,.25,.25,'triangle');sparks(player.x,player.y+1,player.z,0xffa782,15,4);if(player.hp<=0){announce('A MOMENT, NOT THE END','Returning to your last awakened archive.');fallen=1.4;clearInput();}}}
function enemyAttack(e,event){
  if(event.kind==='warning'){if(e.boss)note(110,.2,.1);return;}
  if(event.kind==='wave'){const mesh=new THREE.Mesh(new THREE.RingGeometry(.95,1,96),new THREE.MeshBasicMaterial({color:0xffb583,transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));mesh.rotation.x=-Math.PI/2;mesh.position.set(e.x,.18,e.z);scene.add(mesh);waves.push({mesh,x:e.x,z:e.z,radius:1,speed:event.enraged?14:10,max:20,hit:false,damage:event.damage});ringEffect(e.x,e.z,0xffb583,.5,4,.4);whoosh(true);}
  else if(event.kind==='lance'){const from=new THREE.Vector3(e.x,1,e.z),to=new THREE.Vector3(event.targetX,1,event.targetZ),direction=to.clone().sub(from).normalize();to.addScaledVector(direction,4);const length=from.distanceTo(to),mesh=new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,length,12),new THREE.MeshBasicMaterial({color:0xffc793,transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false}));mesh.position.copy(from.clone().add(to).multiplyScalar(.5));mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),to.clone().sub(from).normalize());scene.add(mesh);effectsList.push({mesh,life:.4,maxLife:.4});if(C.segmentDistance(player.x,player.z,e.x,e.z,to.x,to.z)<1&&player.y<2)damage(event.damage);sparks(event.targetX,1,event.targetZ,0xffbd86,25,4);note(85,.25,.3,'sawtooth');}
  else{ringEffect(event.targetX,event.targetZ,0xff9978,.5,2.6,.3);if(Math.hypot(player.x-event.targetX,player.z-event.targetZ)<2.6&&player.y<1.7)damage(event.damage);whoosh(true);}
}
function collide(){const solids=[...world.colliders,{x:-10,z:4,r:1.2},{x:10,z:4,r:1.2},...C.ISLANDS.map(i=>({x:i.x,z:i.z,r:1.55})),...enemies.filter(e=>!e.dead).map(e=>({x:e.x,z:e.z,r:e.boss?1.8:.6}))];if(player.y>2)return;for(const s of solids){const dx=player.x-s.x,dz=player.z-s.z,d=Math.hypot(dx,dz),r=s.r+.36;if(d<r&&d>.001){player.x=s.x+dx/d*r;player.z=s.z+dz/d*r;}}}
function updatePlayerVisual(dt){
  if(dt<=0)return;
  const speed=Math.hypot(player.vx,player.vz),dashing=player.dashTime>0,k=1-Math.exp(-dt*12);
  flightBlend+=((player.flying?1:0)-flightBlend)*(1-Math.exp(-dt*5));
  motionSpeed+=(Math.min(speed/12,1)-motionSpeed)*k;const moving=motionSpeed;
  const turn=Math.atan2(Math.sin(player.angle-lastFacing),Math.cos(player.angle-lastFacing));lastFacing=player.angle;
  motionBank+=(C.clamp(-turn/Math.max(dt,.016)*.07,-.2,.2)-motionBank)*(1-Math.exp(-dt*7));
  if(player.grounded&&!groundLast)landingSpring=.22;groundLast=player.grounded;landingSpring=Math.max(0,landingSpring-dt);fireCast=Math.max(0,fireCast-dt);
  walkPhase+=dt*(2+Math.min(speed,17)*1.15);const step=Math.sin(walkPhase),breath=Math.sin(time*2)*.014;
  avatar.g.position.set(player.x,player.y,player.z);avatar.g.rotation.y=player.angle;avatar.g.visible=true;
  const dashEnvelope=dashing?Math.sin(Math.PI*(1-player.dashTime/player.dashDuration)):0;
  const crouch=landingSpring>0?Math.sin(landingSpring/.22*Math.PI)*.14:0;
  avatar.body.position.set(step*.045*moving,breath+Math.abs(step)*.045*moving-crouch+dashEnvelope*.18,0);
  avatar.body.rotation.x+=((dashing?.85:.13*moving)-avatar.body.rotation.x)*k;avatar.body.rotation.z=motionBank+Math.sin(walkPhase)*.025*moving;avatar.body.rotation.y=0;
  avatar.head.rotation.y=-motionBank*.7;avatar.head.rotation.x=-avatar.body.rotation.x*.4;
  for(let i=0;i<2;i++){const gait=Math.sin(walkPhase+i*Math.PI);avatar.legs[i].rotation.x=dashing?(i?-.75:.55):player.grounded?gait*.62*moving:(i?-.35:-.8);avatar.knees[i].rotation.x=dashing?1.15:player.grounded?Math.max(0,-gait)*.95*moving+crouch*2:1.05;}
  avatar.arms[0].rotation.set(-step*.48*moving-.1,0,.13+motionBank);avatar.elbows[0].rotation.x=-.2-Math.max(0,step)*.55*moving;
  let pose=ArchiveMotion.rest.slice();pose[0]+=step*.12*moving;pose[3]-=Math.max(0,-step)*.12*moving;
  if(attack&&!attack.air){const p=1-player.attackTime/player.attackDuration;pose=ArchiveMotion.strike(player.combo,p);avatar.body.position.z=Math.sin(p*Math.PI)*.22;avatar.body.rotation.x+=Math.sin(p*Math.PI)*.07;avatar.arms[0].rotation.x=-.5;avatar.elbows[0].rotation.x=-.7;}
  if(dashing){pose=[.25,.15,-.3,-.7,1.1,.1,0];avatar.arms[0].rotation.x=.6;avatar.elbows[0].rotation.x=-.7;}
  if(fireCast>0){const cast=Math.sin(fireCast/.6*Math.PI);avatar.arms[0].rotation.x=-1.3*cast;avatar.elbows[0].rotation.x=-.2;avatar.body.position.y-=cast*.16;pose[2]-=cast*.3;}
  avatar.arms[1].rotation.set(pose[0],pose[1],pose[2]);avatar.elbows[1].rotation.x=pose[3];avatar.sword.rotation.set(pose[4],0,pose[5]);avatar.body.rotation.y=pose[6];
  let weapon=attack&&!attack.air?ArchiveMotion.weapon(player.combo,1-player.attackTime/player.attackDuration):ArchiveMotion.weaponRest.slice();
  if(!attack){weapon[1]+=breath;weapon[2]+=step*.018*moving;}
  if(flightBlend>.001){const forward=Math.min(speed/18,1);avatar.body.rotation.x+=(.18+forward*.85-avatar.body.rotation.x)*flightBlend;avatar.body.rotation.y*=1-flightBlend;avatar.head.rotation.x=-avatar.body.rotation.x*.65;for(let i=0;i<2;i++){avatar.legs[i].rotation.x=avatar.legs[i].rotation.x*(1-flightBlend)-.08*flightBlend;avatar.knees[i].rotation.x=avatar.knees[i].rotation.x*(1-flightBlend)+.16*flightBlend;}if(!attack){const flyingGrip=[0,1.45,.42,.9,0,0];weapon=weapon.map((v,i)=>v+(flyingGrip[i]-v)*flightBlend);}}
  const airborneSuit=player.flying||(!player.grounded&&player.jumps===2);
  avatar.sword.visible=!airborneSuit;
  if(airborneSuit){const target=attack?.air&&attack.target&&!attack.target.dead?new THREE.Vector3(attack.target.x,attack.target.model.targetY,attack.target.z):new THREE.Vector3(player.x+Math.sin(player.angle)*28,player.y+1.4,player.z+Math.cos(player.angle)*28);avatar.aimFlight(target,!!attack?.air);}
  else avatar.holdSword(weapon);
  avatar.flightSuit(flightBlend,time);
  const pos=avatar.cape.geometry.attributes.position;for(let i=0;i<pos.count;i++){const x=avatar.clothBase[i*3],y=avatar.clothBase[i*3+1],f=Math.max(0,-y/1.55);pos.setXYZ(i,x+Math.sin(time*4+f*4)*.06*f+motionBank*f,y,-f*f*(.2+moving*.55+(dashing?1.25:0))+Math.sin(time*7+f*4+x*3)*.09*f);}pos.needsUpdate=true;avatar.cape.geometry.computeVertexNormals();
  avatar.companion.position.lerp(vec.set(player.x-Math.cos(player.angle)*1.15,player.y+2.2+Math.sin(time*2)*.14,player.z+Math.sin(player.angle)*1.15),1-Math.exp(-dt*7));avatar.companion.rotation.y=time;
  avatar.shadow.position.set(player.x,.075,player.z);avatar.shadow.visible=player.y>=0&&C.onGround(player.x,player.z);avatar.shadow.material.opacity=.25/(1+Math.max(0,player.y));avatar.shadow.scale.setScalar(1+Math.max(0,player.y)*.2);
  if(dashing&&dt>0){sparks(player.x,player.y+.9,player.z,0x55d8ec,3,1);for(let n=0;n<3;n++){const p=particles[(particleIndex-1-n+partCount)%partCount];p.vx=-player.dashX*8;p.vz=-player.dashZ*8;p.vy=.3;p.life=p.maxLife=.28;}}
}
function updateEnemies(dt){for(const e of enemies){const m=e.model;if(e.dead){m.warning.visible=false;if(e.deathTime===undefined)continue;e.deathTime+=dt;m.g.scale.setScalar(m.size*Math.max(0,1-e.deathTime/(e.boss?1.8:.8)));m.g.rotation.y+=dt*3;m.g.position.y+=dt*.7;if(e.deathTime>2)m.g.visible=false;continue;}
  const event=C.stepEnemy(e,player,dt);if(event)enemyAttack(e,event);m.g.position.set(e.x,0,e.z);m.g.rotation.y=Math.atan2(player.x-e.x,player.z-e.z);m.coreMat.emissiveIntensity=e.hitFlash>0?3.2:1.4+Math.sin(time*2)*.2;
  const walking=e.phase==='pursue',gait=time*8+e.homeX;for(let i=0;i<2;i++){const step=Math.sin(gait+i*Math.PI);m.legs[i].rotation.x=walking?step*.55:0;m.knees[i].rotation.x=walking?Math.max(0,-step)*.65:0;}
  m.body.position.y=walking?Math.abs(Math.sin(gait))*.035:0;m.body.rotation.x=walking?.12:0;m.arms[0].rotation.x=-.35;m.arms[1].rotation.x=walking?Math.sin(gait)*.3:.12;
  if(e.phase==='windup'){const wind=1-e.timer/e.windupDuration;m.arms[1].rotation.x=-.3-wind*2.3;m.body.rotation.y=wind*.22;}else if(e.phase==='recover'){const swing=Math.max(0,e.timer/(e.boss?.8:.65));m.arms[1].rotation.x=.5-swing*1.3;m.body.rotation.y=-swing*.25;}else m.body.rotation.y=0;
  m.cape.rotation.x=-.12+Math.sin(time*3+e.homeX)*.035;
  m.warning.visible=e.phase==='windup';if(m.warning.visible){const wave=e.boss&&(e.sequence+1)%2===1,r=wave?13:e.boss?2.1:2.6,progress=1-e.timer/e.windupDuration;m.warning.position.set(wave?e.x:e.targetX,.12,wave?e.z:e.targetZ);m.warning.scale.setScalar(r);m.warning.material.opacity=.2+progress*.6;}
}}
function disposeFX(mesh){scene.remove(mesh);mesh.traverse(o=>{o.geometry?.dispose();if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose());}});}
function updateFX(dt){
  for(let i=0;i<partCount;i++){const p=particles[i];p.life=Math.max(0,p.life-dt);if(p.life>0){p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vy-=dt*5;const f=p.life/p.maxLife;particlePositions.set([p.x,p.y,p.z],i*3);particleColors.set([p.color.r*f,p.color.g*f,p.color.b*f],i*3);}else{particlePositions[i*3+1]=-100;particleColors.fill(0,i*3,i*3+3);}}particleMesh.geometry.attributes.position.needsUpdate=true;particleMesh.geometry.attributes.color.needsUpdate=true;
  for(let i=effectsList.length-1;i>=0;i--){const f=effectsList[i];f.life-=dt;const p=1-f.life/f.maxLife,mat=f.material||f.mesh.material;if(mat)mat.opacity=Math.max(0,1-p)*.85;if(f.end)f.mesh.scale.setScalar(f.start+(f.end-f.start)*(1-Math.pow(1-p,2)));if(f.slash)f.mesh.rotation.y+=dt*2;if(f.life<=0){disposeFX(f.mesh);effectsList.splice(i,1);}}
  for(let i=waves.length-1;i>=0;i--){const w=waves[i];w.radius+=dt*w.speed;w.mesh.scale.setScalar(w.radius);w.mesh.material.opacity=.9*(1-w.radius/w.max);if(!w.hit&&Math.abs(Math.hypot(player.x-w.x,player.z-w.z)-w.radius)<.7&&player.y<1.1){damage(w.damage);w.hit=true;}if(w.radius>w.max){disposeFX(w.mesh);waves.splice(i,1);}}
}
function updateCamera(dt){const fov=48+(effects&&player.dashTime>0?5:0)+(effects&&player.flying?3:0);camera.fov+=(fov-camera.fov)*(1-Math.exp(-dt*8));camera.updateProjectionMatrix();yaw+=(targetYaw-yaw)*(1-Math.exp(-dt*7));pitch+=(targetPitch-pitch)*(1-Math.exp(-dt*7));distance+=(targetDistance-distance)*(1-Math.exp(-dt*6));
  if(mode==='title'){const a=.65+(effects?time*.024:0);cameraTarget.set(Math.sin(a)*68,35+(effects?Math.sin(time*.1)*1.5:0),Math.cos(a)*68);lookTarget.set(0,3,-11);}
  else{cameraTarget.set(player.x+Math.sin(yaw)*Math.cos(pitch)*distance,Math.max(-1,player.y)+2+Math.sin(pitch)*distance,player.z+Math.cos(yaw)*Math.cos(pitch)*distance);lookTarget.set(player.x,Math.max(-1,player.y)+1.4,player.z);}
  camera.position.lerp(cameraTarget,1-Math.exp(-dt*(mode==='title'?1.8:7)));if(shake>0){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;shake=Math.max(0,shake-dt*.7);}camera.lookAt(lookTarget);keyLight.position.set(player.x-35,55,player.z-28);keyLight.target.position.set(player.x,0,player.z);
}
const mapContext=$('#minimap').getContext('2d');
function updateMap(){if(!mapContext)return;const c=mapContext,s=1.72,cx=120,cy=133;c.clearRect(0,0,240,240);c.strokeStyle='rgba(187,211,209,.22)';c.lineWidth=3;for(const i of C.ISLANDS){c.beginPath();c.moveTo(cx,cy);c.lineTo(cx+i.x*s,cy+i.z*s);c.stroke();}c.fillStyle='rgba(115,153,158,.14)';c.beginPath();c.arc(cx,cy,14.7*s,0,Math.PI*2);c.fill();c.stroke();for(const i of C.ISLANDS){c.fillStyle=discovered.has(i.id)?'#dac69e':'#708f99';c.beginPath();c.arc(cx+i.x*s,cy+i.z*s,i.r*s*.55,0,Math.PI*2);c.fill();c.fillStyle='#102733';c.font='10px serif';c.textAlign='center';c.fillText(i.chapter,cx+i.x*s,cy+i.z*s+3);}c.save();c.translate(cx+player.x*s,cy+player.z*s);c.rotate(-player.angle);c.fillStyle='#effff8';c.beginPath();c.moveTo(0,6);c.lineTo(-4,-4);c.lineTo(4,-4);c.closePath();c.fill();c.restore();$('#map-coordinates').textContent=`${Math.round(player.x)}° E / ${Math.round(-player.z)}° N`;}
function updateHUD(){
  const flying=player.flying||(!player.grounded&&player.jumps===2);document.body.classList.toggle('in-flight',flying);$('#flight-telemetry').hidden=!flying;$('#flight-speed').textContent=Math.round(Math.hypot(player.vx,player.vz));$('#flight-altitude').textContent=Math.max(0,player.y).toFixed(1);$('#flight-mode').textContent=player.dashTime>0?'BOOST':player.flying?'CRUISE':'LANDING';
  const locked=flying?(attack?.air&&attack.target&&!attack.target.dead?attack.target:enemies.filter(e=>!e.dead&&C.canHitAir(player,{x:e.x,y:e.model.targetY,z:e.z})).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z))[0]):null;
  $('#target-reticle').hidden=true;if(locked){vec.set(locked.x,locked.model.targetY,locked.z).project(camera);const visible=vec.z> -1&&vec.z<1&&Math.abs(vec.x)<1&&Math.abs(vec.y)<1;$('#target-reticle').hidden=!visible;$('#target-reticle').style.left=(vec.x*.5+.5)*innerWidth+'px';$('#target-reticle').style.top=(-vec.y*.5+.5)*innerHeight+'px';$('#target-name').textContent=locked.boss?'WARDEN · LOCKED':'GUARD · LOCKED';$('#target-health').style.width=locked.hp/locked.maxHp*100+'%';}
  for(const e of enemies){if(!e.label)continue;vec.set(e.x,e.model.targetY+1.35,e.z).project(camera);e.label.hidden=e.dead||flying||mode!=='playing'||Math.hypot(e.x-player.x,e.z-player.z)>19||vec.z>1||vec.z< -1;e.label.style.transform=`translate(-50%,-100%) translate(${(vec.x*.5+.5)*innerWidth}px,${(-vec.y*.5+.5)*innerHeight}px)`;e.label.innerHTML=`<small>ASHEN GUARD</small><div><i style="width:${e.hp/e.maxHp*100}%"></i></div>`;}
  $('#jump-button small').textContent=player.flying?'LAND':'JUMP ×2';$('#jump-button').setAttribute('aria-label',player.flying?'Land from flight':'Jump; jump again to activate flight');
  $('#health-label').textContent=Math.ceil(player.hp);$('#health-fill').style.width=player.hp+'%';$('#dash-button').style.setProperty('--cooldown',Math.min(1,player.dashCooldown/.85));$('#dash-status').textContent=player.dashCooldown>0?player.dashCooldown.toFixed(1)+'s':'Dash';$('#dash-button').disabled=player.dashCooldown>0;$('#pulse-button').style.setProperty('--charge',player.resonance+'%');$('#pulse-status').textContent=player.resonance<100?Math.floor(player.resonance)+'%':'Fireburst';$('#pulse-button').disabled=player.resonance<100;$('#discovery-count').textContent=discovered.size+' / 5';
  const next=C.ISLANDS.find(i=>!discovered.has(i.id));$('#objective-kicker').textContent=next?'THE ASTRAL ARCHIVE':'JOURNEY COMPLETE';$('#objective-text').textContent=next?'Awaken the five archives':'Every chapter is open. Keep exploring.';
  const region=C.ISLANDS.find(i=>Math.hypot(player.x-i.x,player.z-i.z)<i.r+1.5);if((region?.id||'hub')!==currentIsland){currentIsland=region?.id||'hub';$('#region-name').textContent=region?.name||'The Confluence';$('#region-sub').textContent=region?.subtitle||'Between worlds, possibility';}
  nearArchive=world.shrines.find(i=>Math.hypot(player.x-i.x,player.z-i.z)<4.5&&player.y<2);$('#interact').hidden=mode!=='playing'||!nearArchive;if(nearArchive)$('#interact').innerHTML=`<kbd>E</kbd> ${discovered.has(nearArchive.id)?'Read':'Awaken'} ${escape(nearArchive.name)} <span>↗</span>`;
  const boss=enemies.find(e=>e.boss),show=boss&&!boss.dead&&Math.hypot(player.x-boss.x,player.z-boss.z)<21;$('#boss-hud').hidden=!show;if(show){$('#boss-health').style.width=boss.hp/boss.maxHp*100+'%';$('#boss-state').textContent=boss.phase==='windup'?((boss.sequence+1)%2?'SHOCKWAVE · JUMP OR DASH':'ASTRAL LANCE · MOVE FROM THE MARK'):boss.hp/boss.maxHp<.5?'AWAKENED · STAY IN MOTION':'THE GATE’S LAST SENTINEL';}
  $('#combo-indicator').textContent=attack?(attack.air?'REPULSOR':['I / FLOW','II / FOLLOW','III / BREAK'][player.combo]):'';
  $('#attack-button small').textContent=player.flying||(!player.grounded&&player.jumps===2)?'REPULSOR':'STRIKE';
  for(const i of world.shrines){vec.set(i.x,6.7,i.z).project(camera);const d=Math.hypot(player.x-i.x,player.z-i.z);i.label.hidden=mode!=='playing'||d>35||d<4||vec.z>1||vec.z< -1;i.label.style.transform=`translate(-50%,-100%) translate(${(vec.x*.5+.5)*innerWidth}px,${(-vec.y*.5+.5)*innerHeight}px)`;i.label.classList.toggle('awakened',i.active);}updateMap();
}
function tick(now){frame=0;if(document.hidden||!ready)return;const raw=lastTime?Math.min(.04,(now-lastTime)/1000):.016;lastTime=now;let dt=paused()?0:raw;if(hitstop>0){hitstop-=raw;dt*=.12;}time+=dt;
  if(travel){travel.t+=raw;if(travel.t>.28&&!travel.moved){const i=travel.island,len=Math.hypot(i.x,i.z);player.x=i.x-i.x/len*4.3;player.z=i.z-i.z/len*4.3;player.y=player.vy=player.vx=player.vz=0;player.grounded=true;player.flying=false;player.jumps=0;flightBlend=0;player.invulnerable=2;player.angle=Math.atan2(i.x-player.x,i.z-player.z);combatFX.clear();travel.moved=true;camera.position.set(player.x+8,10,player.z+10);}if(travel.t>.8){travel=null;$('#transition').classList.remove('active');}}
  if(mode==='playing'&&dt>0){const result=C.stepPlayer(player,movement(),dt);collide();if(result.fell&&!fallen){player.hp=0;fallen=.9;clearInput();announce('THE SKY CATCHES YOU','Returning to your last awakened archive.');}if(fallen){attack=null;attackQueued=false;fallen-=dt;if(fallen<=0){fallen=0;C.respawn(player);combatFX.clear();const b=enemies.find(e=>e.boss);if(!b.dead){b.hp=b.maxHp;b.phase='idle';b.cooldown=2;}for(const w of waves)disposeFX(w.mesh);waves.length=0;ringEffect(player.x,player.z,0xa3efe6,1,5,.8);}}
    if(attack){attack.t+=dt;if(!attack.hit&&attack.t>=attack.delay){attack.hit=true;if(attack.air)repulsorShot(attack);else for(const e of enemies)if(!e.dead&&player.y<4&&C.hitInArc(player,e,attack.range,attack.halfAngle))hitEnemy(e,attack.damage);}if(player.attackTime<=0){attack=null;if(attackQueued){attackQueued=false;doAttack();}}}updateEnemies(dt);
  }
  updatePlayerVisual(dt);updateFX(dt);updateCamera(raw);combatFX.update(dt,time,camera,player,attack,effects);world.animate(time,camera);damageFlash=Math.max(0,damageFlash-raw);$('#damage-flash').style.opacity=damageFlash;announcementTime-=dt;if(announcementTime<=0)$('#announcement').classList.remove('visible');hudTime-=raw;if(hudTime<=0){updateHUD();hudTime=.06;}if(time>20&&mode==='playing')$('#control-hint').classList.add('quiet');composer.render();requestFrame();
}
function requestFrame(){if(!frame&&!document.hidden)frame=requestAnimationFrame(tick);}
$('#begin').onclick=start;$('#title-journal').onclick=$('#journal-button').onclick=()=>{renderJournal();openDialog('journal-dialog');};$('#pause-button').onclick=()=>openDialog('pause-dialog');$('#title-sound').onclick=$('#setting-sound').onclick=toggleSound;
$('#setting-effects').onclick=()=>{effects=!effects;$('#setting-effects span').textContent=effects?'On':'Off';};$('#setting-quality').onclick=()=>{quality=!quality;setQuality();};$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('close',()=>{clearInput();if(mode==='playing')$('#world').focus();}));
$('#dash-button').onclick=doDash;$('#pulse-button').onclick=doPulse;$('#jump-button').onclick=doJump;$('#attack-button').onclick=doAttack;$('#interact').onclick=discover;
addEventListener('keydown',e=>{if($$('dialog').some(d=>d.open))return;if(mode==='title'){if(e.code==='Enter'&&!e.target.closest('button,a'))start();return;}if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Escape')openDialog('pause-dialog');if(e.code==='KeyR'){renderJournal();openDialog('journal-dialog');}if(e.code.startsWith('Shift'))doDash();if(e.code==='Space')doJump();if(['KeyJ','KeyF'].includes(e.code))doAttack();if(e.code==='KeyQ')doPulse();if(e.code==='KeyE')discover();});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',clearInput);
const canvas=$('#world');canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(mode!=='playing'||paused())return;Object.assign(pointer,{active:true,id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false,button:e.button});canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!pointer.active||pointer.id!==e.pointerId)return;if(Math.hypot(e.clientX-pointer.startX,e.clientY-pointer.startY)>5)pointer.moved=true;if(pointer.moved){targetYaw-=(e.clientX-pointer.x)*.006;targetPitch=C.clamp(targetPitch+(e.clientY-pointer.y)*.004,.23,1.05);}pointer.x=e.clientX;pointer.y=e.clientY;});canvas.addEventListener('pointerup',e=>{if(pointer.active&&pointer.id===e.pointerId&&!pointer.moved&&pointer.button===0)doAttack();pointer.active=false;});canvas.addEventListener('pointercancel',()=>pointer.active=false);canvas.addEventListener('wheel',e=>{if(mode==='playing'){e.preventDefault();targetDistance=C.clamp(targetDistance+e.deltaY*.008,8.5,20);}},{passive:false});
const pad=$('#touch-pad');pad.addEventListener('pointerdown',e=>{const r=pad.getBoundingClientRect();Object.assign(stick,{active:true,id:e.pointerId,startX:r.left+r.width/2,startY:r.top+r.height/2});pad.setPointerCapture(e.pointerId);});pad.addEventListener('pointermove',e=>{if(!stick.active||stick.id!==e.pointerId)return;const dx=e.clientX-stick.startX,dz=e.clientY-stick.startY,len=Math.max(38,Math.hypot(dx,dz));stick.x=dx/len;stick.z=dz/len;$('#touch-pad i').style.transform=`translate(${stick.x*30}px,${stick.z*30}px)`;});for(const type of ['pointerup','pointercancel'])pad.addEventListener(type,()=>{stick.active=false;stick.x=stick.z=0;$('#touch-pad i').style.transform='';});
addEventListener('resize',()=>{if(!ready)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();setQuality();});document.addEventListener('visibilitychange',()=>{clearInput();if(document.hidden){cancelAnimationFrame(frame);frame=0;audioContext?.suspend();}else{lastTime=0;if(soundOn)audioContext?.resume();requestFrame();}});
requestAnimationFrame(()=>setTimeout(init,40));
})();
